required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",

  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",
]

[[constraint]]
  branch = "master"
  name = "k8s.io/code-generator"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.8"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.8"
