apiVersion: "kubetidb.gaocegege.com/v1alpha1"
kind: "TiDB"
metadata:
  name: "tidb-cluster-for-test"
spec:
  pd:
    replicas: 1
    template:
      spec:
        containers:
          - name: pd
            image: pingcap/pd:latest
            ports:
              - containerPort: 2379
              - containerPort: 2380
  tikv:
    replicas: 1
    template:
      spec:
        containers:
          - name: tikv
            image: pingcap/tikv:latest
            ports:
              - containerPort: 20160
  tidb:
    replicas: 1
    template:
      spec:
        containers:
          - name: tidb
            image: pingcap/tidb:latest
            ports:
              - containerPort: 4000
              - containerPort: 10080
